#!/usr/bin/env bash
#  Double the number of webservers
sudo apt-get -y update  && sudo apt-get -y install nginx
config="/etc/nginx/sites-available/default"
sudo sed -i "0,/location \/ {/s/location \/ {/&\n\tadd_header X-Served-By '$HOSTNAME';/" $config
sudo service nginx restart
