#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID.

trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit 0;' SIGTERM
trap "rm /var/run/myscript.pid; exit 0;" SIGQUIT
trap 'echo "Y U no love me?!"; exit;' SIGINT

echo $$ > /var/run/myscript.pid
while true; do
	echo "To infinity and beyond"
	sleep 2
done
