#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd.

if [ -r "/etc/passwd" ]; then
    while read -r line; do
        echo "$line" | cut -d ":" -f1,3,6
    done < /etc/passwd
fi
