#!/usr/bin/env bash
# Write a Bash script that configures an Ubuntu server with the below requirements.

cp /etc/hosts ~/myhost
sed -i 's/127.0.0.1\tlocalhost/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/myhost
cp -f ~/myhost /etc/hosts
